<?php

namespace Mpdf\Fonts;

use Mpdf\Cache;
use Mpdf\Exception\FontException;
use Mpdf\TTFontFile;

/**
 * Captures everything TTFontFile hands to Otl for one font, as readable JSON.
 *
 * This is the interface between the two halves of OpenType support: the parser writes these files at
 * font-build time and the shaper reads nothing else. A refactor that leaves every one of them
 * byte-identical cannot have changed what is shaped, whatever it did to the code in between.
 *
 * Deliberately not get_object_vars() on the parser: ~95% of that is charWidths, glyphIDtoUni and
 * glyphToChar, built from cmap and hmtx, which no OTL work touches, and it runs to megabytes per font.
 */
class ParserGoldenMaster
{

	const FIXTURE_DIR = __DIR__ . '/../../data/fontcache';

	const FONT_DIR = __DIR__ . '/../../data/ttf';

	private $tmpDir;

	public function __construct($tmpDir = null)
	{
		$this->tmpDir = $tmpDir === null ? __DIR__ . '/../tmp/mpdf/goldenmaster' : $tmpDir;
	}

	/**
	 * Fonts carrying no GDEF table. TTFontFile refuses these outright when OTL is asked for, so that is
	 * a parser output like any other and is stated here rather than inferred from a missing fixture,
	 * which would read a fixture someone forgot to commit as an expected refusal.
	 */
	private static $noOtlTables = [
		'angerthas',
	];

	/**
	 * Every font in tests/data/ttf, and whether parsing it with OTL enabled is expected to succeed.
	 */
	public function fonts()
	{
		$fonts = [];
		foreach (glob(self::FONT_DIR . '/*.ttf') as $file) {
			$name = basename($file, '.ttf');
			$fonts[$name] = [$name, !in_array($name, self::$noOtlTables, true)];
		}
		ksort($fonts);

		return $fonts;
	}

	public function fixtureFile($name)
	{
		return self::FIXTURE_DIR . '/' . $name . '.json';
	}

	public function hasFixture($name)
	{
		return file_exists($this->fixtureFile($name));
	}

	public function loadFixture($name)
	{
		return file_get_contents($this->fixtureFile($name));
	}

	/**
	 * @return string The fixture as it would be written now, or null if the font has no OTL tables
	 */
	public function capture($name)
	{
		$dir = $this->tmpDir . '/' . $name;
		$this->clear($dir);

		$fontCache = new FontCache(new Cache($dir));
		$ttf = new TTFontFile($fontCache, 'win');

		try {
			$ttf->getMetrics(self::FONT_DIR . '/' . $name . '.ttf', $name, 0, false, false, 0xFF);
		} catch (FontException $e) {
			$this->clear($dir);
			return null;
		}

		$capture = [
			'_' => 'Generated by composer fontcache:update. See tests/Mpdf/Fonts/ParserGoldenMaster.php.',
			'fullName' => $ttf->fullName,
			'mtx' => [
				'GSUBScriptLang' => $ttf->GSUBScriptLang,
				'GSUBFeatures' => $ttf->GSUBFeatures,
				'GSUBLookups' => $ttf->GSUBLookups,
				'GPOSScriptLang' => $ttf->GPOSScriptLang,
				'GPOSFeatures' => $ttf->GPOSFeatures,
				'GPOSLookups' => $ttf->GPOSLookups,
				'MarkGlyphSets' => $ttf->MarkGlyphSets,
				'rtlPUAstr' => $ttf->rtlPUAstr,
				'haskernGPOS' => (bool) $ttf->haskernGPOS,
				'hassmallcapsGSUB' => (bool) $ttf->hassmallcapsGSUB,
			],
			'cache' => $this->cacheFiles($dir, $name),
		];

		$this->clear($dir);

		return json_encode($capture, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
	}

	public function update($name)
	{
		$capture = $this->capture($name);
		$file = $this->fixtureFile($name);

		if ($capture === null) {
			if (file_exists($file)) {
				unlink($file);
			}

			return null;
		}

		if (!is_dir(self::FIXTURE_DIR)) {
			mkdir(self::FIXTURE_DIR, 0777, true);
		}

		file_put_contents($file, $capture);

		return $file;
	}

	/**
	 * The cache as the shaper will find it: JSON decoded so a diff is readable, the concatenated
	 * GSUB/GPOS blob by length and hash because it is a copy of the font's own bytes.
	 */
	private function cacheFiles($dir, $name)
	{
		$files = [];
		foreach (glob($dir . '/' . $name . '.*') as $file) {
			$key = substr(basename($file), strlen($name) + 1);
			if (substr($key, -5) === '.json') {
				$files[$key] = json_decode(file_get_contents($file), true);
			} else {
				$files[$key] = sprintf('%d bytes, sha256 %s', filesize($file), hash_file('sha256', $file));
			}
		}
		ksort($files);

		return $files;
	}

	private function clear($dir)
	{
		if (!is_dir($dir)) {
			return;
		}

		foreach (glob($dir . '/*') as $file) {
			if (is_file($file)) {
				unlink($file);
			}
		}
	}
}
